version: '3.8'

services:

  auth:
    build: ./auth
    restart: always
    command: uvicorn auth.main:app --host 0.0.0.0
    ports:
      - 8188:8000

  data_grip:
    build: ./data_grip
    restart: always
    command: uvicorn data_grip.main:app --host 0.0.0.0
    ports:
      - 8180:8000
  # db:
  #   restart: always
  #   image: postgres:11.11
  #   # Внешний том(volume) и место где он будет подключен внутри контейнера
  #   volumes:
  #     - ./db/:/var/lib/postgresql/data/
  #   ports:
  #     - 5435:5432
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=biji