version: '3.8'

services:

  auth:
    build: ./auth
    # image: shureck/sber-auth:latest
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8001
    ports:
      - 8188:8001
    networks:
      - sber-network
      
  data_grip:
    build: ./data_grip
    # image: shureck/sber-data:latest
    restart: always
    command: uvicorn fast_main:app --host 0.0.0.0
    ports:
      - 8180:8000
    networks:
      - sber-network

  krakend:
    container_name: krakend
    build: ./krakend 
    restart: always
    ports:
      - "8190:8090"
    networks:
      - sber-network

networks:
  sber-network:
    driver: bridge
  # db:
  #   restart: always
  #   image: postgres:11.11
  #   # Внешний том(volume) и место где он будет подключен внутри контейнера
  #   volumes:
  #     - ./db/:/var/lib/postgresql/data/
  #   ports:
  #     - 5435:5432
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=biji