name: Build and Push

on:
  push:
    branches:
      - main
      
jobs:
  job1:
    name: Build auth
    runs-on: ubuntu-latest
    env:
      LOGIN: ${{ secrets.DOCKERHUB_LOGIN }}
      NAME: ${{ secrets.DOCKER_NAME_1 }}
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build -t $LOGIN/$NAME:latest ./auth
      - name: Docker login
        run: echo ${{ secrets.DOCKERHUB_PASS }} | docker login -u ${{ secrets.DOCKERHUB_LOGIN }} --password-stdin
      - name: Push image
        run: docker push $LOGIN/$NAME:latest
  job2:
    name: Build data
    runs-on: ubuntu-latest
    env:
      LOGIN: ${{ secrets.DOCKERHUB_LOGIN }}
      NAME: ${{ secrets.DOCKER_NAME_2 }}
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build -t $LOGIN/$NAME:latest ./data_grip
      - name: Docker login
        run: echo ${{ secrets.DOCKERHUB_PASS }} | docker login -u ${{ secrets.DOCKERHUB_LOGIN }} --password-stdin
      - name: Push image
        run: docker push $LOGIN/$NAME:latest
  job3:
    name: Publish
    needs: [job1,job2]
    runs-on: ubuntu-latest
    steps:
        - name: Run sshpass commands
          uses: matheusvanzan/sshpass-action@v2
          with:
            host: ${{ secrets.VIRTUAL_IP }}
            user: ${{ secrets.VIRTUAL_LOGIN }}
            pass: ${{ secrets.VIRTUAL_PASS }}
            run: |
              cd sber-back
              docker compose pull
              docker compose up -d
